config/routes.rb
Store::Application.routes.draw do
  get "home/index"

  resources :products do
    member do
      get "add_to_cart"
    end
  end

  root :to => 'home#index'

end

app/models/.#cart.rb
lukasz@lukasz-ThinkPad-T61.7557:1329946468

app/models/cart.rb
class Cart

  attr_reader :items
  attr_writer :items

  def initialize(items)
    items = { } if items.nil?
    @items = items
  end

  # adding items to cart
  def add_item(item)
    if @items.has_key? item.id.to_s
      value = (@items[item.id.to_s].to_i + 1).to_s
      @items[item.id.to_s] = value
    else
      @items.update({ item.id.to_s => '1' })
    end
  end

  # removing items from cart
  def remove_item(item)
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true

end

app/models/product_flymake.rb
class Product < ActiveRecord::Base
  validates :name, :presence => true
  validates :description, :presence => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def find_cart
    @_cart ||= Cart.new(session[:cart])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(params[:product])
    @product.save
    redirect_to products_path
  end

  def update
  end

  def edit
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  def add_to_cart
    @product = Product.find(params[:id])
    @cart = find_cart
    @cart.add_item @product
    session[:cart] = @cart.items
    redirect_to products_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>OK JAZDA!</p>
<%= link_to "products managment", products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%- flash.each do |name, mesg| -%>
  <%= content_tag :div, msg, :id => "flash_#{name}" %>
<%- end -%>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for @product do |f|%>
  <%= f.label :name %><br />
  <%= f.text_field :name %><br />
  <%= f.label :description %><br />
  <%= f.text_area :description %><br />
  <%= f.submit %>
<% end %>

app/views/products/index.html.erb
Products list:<br /><br />
<% if session[:cart].nil?%>
  session cart is empty
<% else %>
<%= session[:cart].to_s %>
<% end %>
<br />
<% @products.each do |product| %>
  <%= link_to product.name, product_path(product) %> |
  <%= product.description %> |
  <%= link_to 'Add to Cart', add_to_cart_product_path(product) %>
  <%= link_to 'Destroy', product_path(product), :method => :delete %><br />
<% end %>

<%= link_to "New Product", new_product_path %>

app/views/products/new.html.erb
this is view for creating new product<br /><br />

<%= render "form" %><br />
<%= link_to "back", :back %>

app/views/products/show.html.erb
<%= params %><br />
<%= params[:id]%><br />
Name:<br />
<%= @product.name %><br />
Desc:<br />
<%= @product.description %><br />